name: Step 0 # Start Exercise

on:
  push:
    branches:
      - main

permissions:
  contents: write # Update Readme
  actions: write # Disable/enable workflows
  issues: write # Create issue and comment on issues


env:
  STEP_1_FILE: ".github/steps/1-create-a-branch.md"

jobs:
  start_exercise:
    if: |
      !github.event.repository.is_template
    name: Start Exercise
    uses: skills/exercise-toolkit/.github/workflows/start-exercise.yml@v0.1.0
    with:
      exercise-title: "Introduction to GitHub"
      intro-message: "If you are new to GitHub, you might find your fellow developers use ___**issues**___  to organize their work and collaborate. We will do the same! That's another lesson, but today, we will introduce you to the basics."


  post_next_step_content:
    name: Post next step content
    runs-on: ubuntu-latest
    needs: [start_exercise]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Post next step content
        uses: ./.github/actions/next-step
        with:
          issue_url: ${{ needs.start_exercise.outputs.issue-url }}
          step_file_path: ${{ env.STEP_1_FILE }}
          next_workflow_file_or_name: "1-create-a-branch.yml"
          gh_token: ${{ secrets.GITHUB_TOKEN }}
